In [1]:
from pymongo import MongoClient
import pandas as pd
client = MongoClient()
client = MongoClient(host="localhost", port=27017)

In [2]:
db = client['Amusement_Park']

## Query - 1
### Find all activities in the rides collection

In [4]:
collection1 = db["RIDES"]
result1 = collection1.find({})
df1 = pd.DataFrame(result1)
df1

,_id,Activity_ID,Entry_Cost_in_USD,Wait_Time_in_Minutes
0,656bcb58d8ad4d31e632a89b,ACT001,5,13
1,656bcb58d8ad4d31e632a89c,ACT002,5,20
2,656bcb58d8ad4d31e632a89d,ACT003,15,5
3,656bcb58d8ad4d31e632a89e,ACT004,10,10
4,656bcb58d8ad4d31e632a89f,ACT005,4,5
5,656bcb58d8ad4d31e632a8a0,ACT006,6,9
6,656bcb58d8ad4d31e632a8a1,ACT007,8,19
7,656bcb58d8ad4d31e632a8a2,ACT008,5,7
8,656bcb58d8ad4d31e632a8a3,ACT009,15,19
9,656bcb58d8ad4d31e632a8a4,ACT010,15,12
10,656bcb58d8ad4d31e632a8a5,ACT011,9,16
11,656bcb58d8ad4d31e632a8a6,ACT012,4,17
12,656bcb58d8ad4d31e632a8a7,ACT013,6,10
13,656bcb58d8ad4d31e632a8a8,ACT014,10,6
14,656bcb58d8ad4d31e632a8a9,ACT015,14,19
15,656bcb58d8ad4d31e632a8aa,ACT016,15,16
16,656bcb58d8ad4d31e632a8ab,ACT017,12,16
17,656bcb58d8ad4d31e632a8ac,ACT018,13,7
18,656bcb58d8ad4d31e632a8ad,ACT019,5,9
19,656bcb58d8ad4d31e632a8ae,ACT020,10,8
20,656bcb58d8ad4d31e632a8af,ACT021,13,14
21,656bcb58d8ad4d31e632a8b0,ACT022,8,15
22,656bcb58d8ad4d31e632a8b1,ACT023,5,5
23,656bcb58d8ad4d31e632a8b2,ACT024,11,6
24,656bcb58d8ad4d31e632a8b3,ACT025,15,5
25,656bcb58d8ad4d31e632a8b4,ACT026,10,14
26,656bcb58d8ad4d31e632a8b5,ACT027,3,15
27,656bcb58d8ad4d31e632a8b6,ACT028,14,19
28,656bcb58d8ad4d31e632a8b7,ACT029,11,19
29,656bcb58d8ad4d31e632a8b8,ACT030,10,12
30,656bcb58d8ad4d31e632a8b9,ACT031,4,5
31,656bcb58d8ad4d31e632a8ba,ACT032,13,10
32,656bcb58d8ad4d31e632a8bb,ACT033,12,10
33,656bcb58d8ad4d31e632a8bc,ACT034,5,17
34,656bcb58d8ad4d31e632a8bd,ACT035,13,16
35,656bcb58d8ad4d31e632a8be,ACT036,6,8
36,656bcb58d8ad4d31e632a8bf,ACT037,12,13
37,656bcb58d8ad4d31e632a8c0,ACT038,4,8
38,656bcb58d8ad4d31e632a8c1,ACT039,9,10
39,656bcb58d8ad4d31e632a8c2,ACT040,3,8
40,656bcb58d8ad4d31e632a8c3,ACT041,9,14
41,656bcb58d8ad4d31e632a8c4,ACT042,13,12
42,656bcb58d8ad4d31e632a8c5,ACT043,8,8
43,656bcb58d8ad4d31e632a8c6,ACT044,15,15
44,656bcb58d8ad4d31e632a8c7,ACT045,6,6
45,656bcb58d8ad4d31e632a8c8,ACT046,8,13
46,656bcb58d8ad4d31e632a8c9,ACT047,7,14
47,656bcb58d8ad4d31e632a8ca,ACT048,11,5

## Query 2
### Find customers who provided feedback with ratings greater than 4.

In [5]:
collection2 = db["FEEDBACK"]
query = {"Ratings": {"$gt": 4}}
result = collection2.find(query)
df2 = pd.DataFrame(result)
df2

,_id,Feedback_ID,Activity_ID,Activity_Name,Ratings,Customer_ID
0,656c0f72d8ad4d31e632a973,2,ACT021,The Wild One (roller coaster),5,480
1,656c0f72d8ad4d31e632a975,4,ACT023,Jack Rabbit (Kennywood),5,200
2,656c0f72d8ad4d31e632a976,5,ACT024,Jack Rabbit (Seabreeze),5,520
3,656c0f72d8ad4d31e632a97a,9,ACT028,Wild Cat (Hersheypark),5,579
4,656c0f72d8ad4d31e632a97e,13,ACT032,The Thriller (roller coaster),5,136
...,...,...,...,...,...,...
186,656c0f72d8ad4d31e632ad2d,956,ACT035,Cyclone (Revere Beach),5,556
187,656c0f72d8ad4d31e632ad32,961,ACT059,Attire Stall,5,249
188,656c0f72d8ad4d31e632ad4a,985,ACT008,Figure Eight (Euclid Beach Park),5,896
189,656c0f72d8ad4d31e632ad4c,987,ACT034,Big Dipper (Geauga Lake),5,752
190,656c0f72d8ad4d31e632ad59,1000,ACT059,Attire Stall,5,264

## Query 3
### Calculate average ratings per activity.

In [6]:
map_reduce_result = db.command({
    'mapReduce': 'FEEDBACK',
    'map': 'function() { emit(this.Activity_ID, this.Ratings); }',
    'reduce': 'function(key, value) { return Array.sum(value) / value.length; }',
    'out': {'inline': 1},
    'finalize': 'function(key, reducedValue) { var roundedValue = Math.round(reducedValue * 100) / 100; return roundedValue ; }'
})

df3 = pd.DataFrame(map_reduce_result['results'])
df3.rename(columns={'value': 'Average_Ratings'}, inplace=True)
df3

       _id  Average_Ratings
0   ACT018             2.83
1   ACT042             2.45
2   ACT013             2.59
3   ACT008             2.31
4   ACT031             3.06
5   ACT022             2.89
6   ACT041             2.60
7   ACT054             2.89
8   ACT056             2.89
9   ACT010             2.77
10  ACT051             2.71
11  ACT017             3.00
12  ACT012             3.60
13  ACT036             3.55
14  ACT014             3.11
15  ACT046             3.47
16  ACT004             3.10
17  ACT059             3.04
18  ACT026             2.93
19  ACT028             2.69
20  ACT058             2.92
21  ACT053             2.93
22  ACT007             3.00
23  ACT052             3.43
24  ACT001             2.45
25  ACT037             3.07
26  ACT039             2.60
27  ACT057             2.68
28  ACT021             3.45
29  ACT005             2.87
30  ACT055             3.09
31  ACT047             2.58
32  ACT048             2.73
33  ACT016             3.14
34  ACT009             2.78
35  ACT019             2.61
36  ACT038             2.92
37  ACT050             3.30
38  ACT043             3.18
39  ACT025             3.13
40  ACT015             2.69
41  ACT024             3.53
42  ACT003             3.25
43  ACT029             3.53
44  ACT044             3.29
45  ACT020             3.18
46  ACT040             3.20
47  ACT033             3.12
48  ACT049             2.79
49  ACT011             3.00
50  ACT023             3.63
51  ACT006             3.10
52  ACT035             2.89
53  ACT002             2.88
54  ACT032             3.53
55  ACT030             2.50
56  ACT045             3.25
57  ACT027             2.94
58  ACT034             2.62